/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

/**
 *
 * @author devis
 */

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
public class Allowance extends javax.swing.JFrame {

    /**
     * Creates new form Allowance
     */
    public Allowance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        bpay = new javax.swing.JTextField();
        bonus = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tamt = new javax.swing.JTextField();
        leave = new javax.swing.JTextField();
        medical = new javax.swing.JTextField();
        ded = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        appr = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 208, 131));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(131, 170, 247));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("EMPLOYEE ID: ");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(160, 20, 130, 17);

        search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(search);
        search.setBounds(301, 11, 280, 38);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 51));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(850, 10, 73, 25);

        jButton4.setBackground(new java.awt.Color(153, 153, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Search");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(600, 10, 90, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 50, 930, 60);

        jPanel3.setBackground(new java.awt.Color(131, 170, 247));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("EMP ID:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(90, 80, 60, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("First name: ");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(80, 130, 70, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Basic Pay: ");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(90, 180, 70, 15);
        jPanel3.add(jLabel5);
        jLabel5.setBounds(99, 178, 0, 0);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Appraisals: ");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(90, 230, 70, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Bonus: ");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(90, 270, 70, 23);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/appraisal-form.png"))); // NOI18N
        jPanel3.add(jLabel8);
        jLabel8.setBounds(390, 0, 80, 80);
        jPanel3.add(id);
        id.setBounds(170, 70, 130, 30);
        jPanel3.add(fname);
        fname.setBounds(170, 120, 130, 30);
        jPanel3.add(bpay);
        bpay.setBounds(170, 170, 130, 30);

        bonus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bonus.setText("00.00");
        bonus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bonusActionPerformed(evt);
            }
        });
        jPanel3.add(bonus);
        bonus.setBounds(170, 270, 130, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Over time:");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(90, 340, 80, 15);

        jSpinner1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel3.add(jSpinner1);
        jSpinner1.setBounds(170, 330, 130, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Leaves:");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(480, 60, 60, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Medical:");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(480, 110, 50, 15);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Other deductions:");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(480, 150, 120, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Total Amount:");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(470, 210, 140, 22);

        tamt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tamt.setText("00.00");
        jPanel3.add(tamt);
        tamt.setBounds(630, 200, 170, 40);

        leave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        //leave.setText("0");
        jPanel3.add(leave);
        leave.setBounds(610, 50, 130, 30);

        medical.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        medical.setText("00.00");
        jPanel3.add(medical);
        medical.setBounds(610, 100, 130, 30);

        ded.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ded.setText("00.00");
        jPanel3.add(ded);
        ded.setBounds(610, 150, 130, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("CALCULATE");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(480, 290, 150, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("clear");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(670, 290, 130, 40);

        appr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        appr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Traditional", "perforamance" }));
        appr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                apprMouseExited(evt);
            }
        });
        jPanel3.add(appr);
        appr.setBounds(170, 220, 130, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 140, 930, 384);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1003, 607));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // back tp main menu
        Adminhome adh = new Adminhome();
        adh.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //search 
        String s =search.getText();
        try{
            Connector c1= new Connector();
            String sql="select * from employee_info as e,leaves as l,allowance as a where e.emp_id='"+s+"' and l.emp_id='"+s+"'and a.emp_id='"+s+"'";
            ResultSet rs = c1.s.executeQuery(sql);
            while(rs.next()){
            	String a = rs.getString("days");
                leave.setText(a);
            String add1=rs.getString("emp_id");
            id.setText(add1);
            String add2=rs.getString("first_name");
            fname.setText(add2);
             String add12=rs.getString("basic_pay");
            bpay.setText(add12);
            	String sk = rs.getString("status");
            	
           String abc = rs.getString("final_pay");
            
            if(sk.equals("paid")) { 
            	//JOptionPane.showMessageDialog(null,"This employee has already been paid.'"+abc+"' amount");
            	tamt.setText(abc);
            	jButton2.setEnabled(false);
               
            }
            else {
            	
            	jButton2.setEnabled(true);
            	tamt.setText("0");
            }
            
            
            
            
            }
            
        }
        catch(Exception e){
            e.printStackTrace();
        }
        
        
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // calc button 
    	
    	
    	
    	
         int salary= Integer.parseInt(bpay.getText());
         //int time =Integer.parseInt(overtime.getText());
         Object ge=appr.getSelectedItem();
           String g =ge.toString();
           double bonu=Double.parseDouble(bonus.getText());
           double other =Double.parseDouble(ded.getText());
           double lea=Double.parseDouble(leave.getText());
           Integer overtime = (Integer) jSpinner1.getValue();
           double med =Double.parseDouble(medical.getText());
           if(g.equals("Traditional")){
               double final_pay = salary+2500+bonu+overtime*400-lea*1000-other-med;
               String c =String.valueOf(final_pay);
               tamt.setText(c);
           }
           else{
               double final_pay = salary+3500+bonu+overtime*400-lea*1000-other-med;
               String c =String.valueOf(final_pay);
               tamt.setText(c);
               
           }
           
           
           try{ 
               String s = search.getText();
               Connector c  = new Connector();
               
                 String a = bpay.getText();
                  Object gb=appr.getSelectedItem();
           String gx =gb.toString();
                 
                String fn=fname.getText();
                String i=id.getText();
               
                String b=bonus.getText();
                String l=leave.getText();
                String m=medical.getText();
                String d=ded.getText();
                String ta=tamt.getText();
                Integer ot = (Integer) jSpinner1.getValue();
                
                	 String sq="update month_details set deduction='"+d+"',total_pay='"+ta+"' where emp_id='"+i+"'";
                     String sql1 ="update allowance set leaves='"+l+"',hike='"+gx+"',bonus='"+b+"',overtime='"+ot+"',final_pay='"+ta+"',medical='"+m+"',deductions='"+d+"',status='"+"paid"+"'  where emp_id='"+i+"'and status='"+"not paid"+"'";
                     c.s.execute(sql1);
                     c.s.execute(sq);
                     JOptionPane.showMessageDialog(null,"saved and claculated succesfully");
                
               
               
           }catch(Exception e){
               e.printStackTrace();
               JOptionPane.showMessageDialog(null," unsuccesfull");
               
           }
           
           //int a= salary +app;
           String sql1 ="insert into allowance (emp_id,first_name,basic_pay,apprisals,bonus,leaves,medical,other)";
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void apprMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apprMouseExited
        // TODO add your handling code here:
       //no use
  
        
        
    }//GEN-LAST:event_apprMouseExited

    private void bonusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bonusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bonusActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ///  clear all
        bpay.setText("");
        fname.setText("");
        id.setText("");
        search.setText("");
        bonus.setText("");
        leave.setText("");
        medical.setText("");
        ded.setText("");
        tamt.setText("");
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Allowance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Allowance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Allowance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Allowance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Allowance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> appr;
    private javax.swing.JTextField bonus;
    private javax.swing.JTextField bpay;
    private javax.swing.JTextField ded;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField leave;
    private javax.swing.JTextField medical;
    private javax.swing.JTextField search;
    private javax.swing.JTextField tamt;
    // End of variables declaration//GEN-END:variables
}
