/*
   * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

/**
 *
 * @author devis
 */
import java.sql.*;
import javax.swing.*;
import java.text.SimpleDateFormat;  
import java.util.Date;  
public class employeeadd extends javax.swing.JFrame {

    /**
     * Creates new form employeeadd
     */
    public employeeadd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        id = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        phno = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        addr = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        desig = new javax.swing.JComboBox<>();
        bpay = new javax.swing.JTextField();
        accno = new javax.swing.JTextField();
        pan = new javax.swing.JTextField();
        dob = new com.toedter.calendar.JDateChooser();
        jButton4 = new javax.swing.JButton();
        hdate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(158, 242, 150));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(151, 240, 238));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Employee ID:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(180, 20, 110, 17);

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel2.add(search);
        search.setBounds(290, 10, 230, 30);

        jButton5.setBackground(new java.awt.Color(151, 240, 238));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 51, 51));
        jButton5.setText("HOME");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(850, 10, 90, 30);

        jButton6.setBackground(new java.awt.Color(102, 255, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButton6.setText("search");
        jButton6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 255, 255), null, null));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(540, 10, 80, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 6, 950, 60);

        jPanel3.setBackground(new java.awt.Color(234, 152, 240));
        jPanel3.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile(2).png"))); // NOI18N
        jPanel3.add(jLabel2);
        jLabel2.setBounds(404, 23, 64, 72);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Emloyee ID:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(60, 95, 80, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("First name:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(60, 150, 70, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Last Name:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(60, 200, 80, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Gender: ");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(60, 250, 50, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Date of Birth:");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(60, 300, 80, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Phone number:");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(60, 350, 90, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Email:");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(60, 400, 40, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Adress: ");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(60, 450, 60, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("City:");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(60, 500, 40, 15);

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        gender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(gender);
        gender.setBounds(160, 240, 150, 30);
        jPanel3.add(id);
        id.setBounds(160, 90, 150, 30);
        jPanel3.add(fname);
        fname.setBounds(160, 140, 150, 30);
        jPanel3.add(lname);
        lname.setBounds(160, 190, 150, 30);
        jPanel3.add(phno);
        phno.setBounds(160, 340, 150, 30);
        jPanel3.add(email);
        email.setBounds(160, 390, 150, 30);
        jPanel3.add(addr);
        addr.setBounds(160, 440, 150, 30);
        jPanel3.add(city);
        city.setBounds(160, 490, 150, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Designation:");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(510, 90, 80, 15);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Basic Pay :");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(510, 140, 70, 15);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Hiring date:");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(510, 200, 70, 15);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("ACC no:");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(510, 250, 70, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("PAN:");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(510, 290, 50, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(510, 330, 110, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(510, 400, 110, 50);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(720, 330, 110, 50);

        desig.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        desig.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Junior", "senior", "leader", "manager", "other" }));
        jPanel3.add(desig);
        desig.setBounds(620, 81, 79, 30);
        jPanel3.add(bpay);
        bpay.setBounds(620, 140, 130, 30);
        jPanel3.add(accno);
        accno.setBounds(620, 240, 130, 30);

        pan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panActionPerformed(evt);
            }
        });
        jPanel3.add(pan);
        pan.setBounds(620, 280, 130, 30);
        jPanel3.add(dob);
        dob.setBounds(160, 290, 150, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("CLEAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(720, 400, 110, 50);
        jPanel3.add(hdate);
        hdate.setBounds(620, 190, 130, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 80, 950, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 971, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(995, 680));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        // TODO add your handling code here:
        /// search codeString s =search.getText();
       
        
        
        
        
    }//GEN-LAST:event_searchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        /// adding into database 
        try{
            Connector c1 = new Connector();
            String ida=id.getText();
           String fname1=fname.getText();
           
           
           String lname1=lname.getText();
           
           Object ge=gender.getSelectedItem();
           String g =ge.toString();
           SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
           String db= df.format(dob.getDate());
           String ph=phno.getText();
           String em=email.getText();
           String adrr=addr.getText();
           String cit=city.getText(); 
           String hd= df.format(hdate.getDate());
           String acc=accno.getText();       
          String p=pan.getText();
           Object des=desig.getSelectedItem();
           String pay=bpay.getText();
           
           String des1=des.toString();
         if(fname1.equals("") || fname1.contains("1") || fname1.contains("2") || fname1.contains("3") || fname1.contains("4") || fname1.contains("5") || fname1.contains("6") || fname1.contains("7") || fname1.contains("8") || fname1.contains("9") || fname1.contains("0")){
                JOptionPane.showMessageDialog(null,"fname should not be null or incorrect type !");
           }
         else if(lname1.equals("") || lname1.contains("1") || lname1.contains("2") || lname1.contains("3") || lname1.contains("4") || lname1.contains("5") || lname1.contains("6") || lname1.contains("7") || lname1.contains("8") || lname1.contains("9") || lname1.contains("0")){
             JOptionPane.showMessageDialog(null,"lname should not be null or incorrect type !");
           }
         else if(ph.equals("") || ph.contains("a") || ph.contains("b") || ph.contains("c") || ph.contains("d") || ph.contains("e") || ph.contains("v") || ph.contains("u") || ph.contains("x") || ph.contains("y") || ph.contains("z")){
             JOptionPane.showMessageDialog(null,"phno should not be null or incorrect type !");
           }
         else if(em.equals("")){
                JOptionPane.showMessageDialog(null,"email should not be null or incorrect type !");
           }
         else if(adrr.equals("")){
                JOptionPane.showMessageDialog(null,"addr should not be null or incorrect type !");
           }
         else if(pay.equals("") || pay.contains("a") || pay.contains("b") || pay.contains("c") || pay.contains("d") || pay.contains("e") || pay.contains("v") || pay.contains("u") || pay.contains("x") || pay.contains("y") || pay.contains("z")){
             JOptionPane.showMessageDialog(null,"basic pay number should not be null or incorrect type !");
           }
         else if(acc.equals("")|| acc.contains("a") || acc.contains("b") || acc.contains("c") || acc.contains("d") || acc.contains("e") || acc.contains("v") || acc.contains("u") || acc.contains("x") || acc.contains("y") || acc.contains("z")){
             JOptionPane.showMessageDialog(null,"acc number should not be null or incorrect type !");
           }
           

               else{
         String sql = "insert into employee_info(emp_id,first_name,last_name,gender,dob,phno,email,address,city,designation,basic_pay,startdate,accno,pan)values('"+ida+"','"+fname1+"','"+lname1+"','"+g+"','"+db+"','"+ph+"','"+em+"','"+adrr+"','"+cit+"','"+des1+"','"+pay+"','"+hd+"','"+acc+"','"+p+"')";
         String sql1="insert into leaves(emp_id,days)values('"+ida+"','"+"0"+"')";
         String sql2 = "insert into allowance(emp_id,first_name,phno) values ('"+ida+"','"+fname1+"','"+ph+"')";
         //String sql3="create table ('"+fname1+"') (emp_id primary key,date varchar(10),status varchar(10))";
         String sq="insert into month_details(emp_id,emp_name,email,designation,basic_pay) values('"+ida+"','"+fname1+"','"+em+"','"+des1+"','"+pay+"')";
         c1.s.execute(sql);
         c1.s.execute(sq);
         JOptionPane.showMessageDialog(null,"success !");
         c1.s.execute(sql1);
         c1.s.execute(sql2);
         //c1.s.execute(sql3);
                       
           }
        }catch(Exception e){
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        // home page
        Adminhome ad= new Adminhome();
        ad.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        // delete the record
           try{
            String s =search.getText();
            if(!s.equals("")){
            Connector c1= new Connector();
           String sql="delete from employee_info where emp_id='"+s+"'";
           
          int re=JOptionPane.showConfirmDialog(null,"confirm","Are you sure you want to delete",JOptionPane.YES_NO_OPTION,JOptionPane.ERROR_MESSAGE);
           if(re==0){
        	String sql1="delete from allowance where emp_id='"+s+"'";
        	String sql2="delete from leaves where emp_id='"+s+"'";
        	String sql3="delete from logs where emp_id='"+s+"'";
        	String sql4="delete from month_details where emp_id='"+s+"'";
           c1.s.execute(sql);
           c1.s.execute(sql1);
           c1.s.execute(sql2);
           c1.s.execute(sql3);
           c1.s.execute(sql4);
           
           JOptionPane.showMessageDialog(null,"record deleted succesfully");}
           else{
              JOptionPane.showMessageDialog(null,"record not deleted");  
            }
   
            }
            else{
                JOptionPane.showMessageDialog(null,"empty box");
            }
            
        
        }
       catch(Exception e){
           e.printStackTrace();
                      JOptionPane.showMessageDialog(null,"record not deleted");
        
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        /// clearing text fileds
        search.setText("");
        id.setText("");
        fname.setText("");
        lname.setText("");
        //gender.setText("");
        //dob.setText("");
         dob.setCalendar (null); 
        phno.setText("");
        email.setText("");
        addr.setText("");
        city.setText("");
       // pincode.setText("");
        //desig.setText("");
        bpay.setText("");
        //dept.setText("");
       //status.setText("");
        hdate.setCalendar(null);
        accno.setText("");
        //bankname.setText("");
       // ifsc.setText("");
        //aadhaar.setText("");
        pan.setText("");
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // upadate the db 
         try{
            String s =search.getText();
            if(!s.equals("")){
            
            Connector c1= new Connector();
            String ida=id.getText();
           String fname1=fname.getText();
           String lname1=lname.getText();
           Object ge=gender.getSelectedItem();
           String g =ge.toString();
           SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
           String db= df.format(dob.getDate());
           String ph=phno.getText();
           String em=email.getText();
           String adrr=addr.getText();
           String cit=city.getText(); 
           Object des=desig.getSelectedItem();
           String des1=des.toString();
           String pay=bpay.getText();
           String hd= df.format(hdate.getDate());          
           String acc=accno.getText();
        
          String p=pan.getText();
          
          if(fname1.equals("") || fname1.contains("1") || fname1.contains("2") || fname1.contains("3") || fname1.contains("4") || fname1.contains("5") || fname1.contains("6") || fname1.contains("7") || fname1.contains("8") || fname1.contains("9") || fname1.contains("0")){
              JOptionPane.showMessageDialog(null,"fname should not be null or incorrect type !");
         }
       else if(lname1.equals("") || lname1.contains("1") || lname1.contains("2") || lname1.contains("3") || lname1.contains("4") || lname1.contains("5") || lname1.contains("6") || lname1.contains("7") || lname1.contains("8") || lname1.contains("9") || lname1.contains("0")){
           JOptionPane.showMessageDialog(null,"lname should not be null or incorrect type !");
         }
       else if(ph.equals("") || ph.contains("a") || ph.contains("b") || ph.contains("c") || ph.contains("d") || ph.contains("e") || ph.contains("v") || ph.contains("u") || ph.contains("x") || ph.contains("y") || ph.contains("z")){
           JOptionPane.showMessageDialog(null,"phno should not be null or incorrect type !");
         }
       else if(em.equals("")){
              JOptionPane.showMessageDialog(null,"email should not be null or incorrect type !");
         }
       else if(adrr.equals("")){
              JOptionPane.showMessageDialog(null,"addr should not be null or incorrect type !");
         }
       else if(pay.equals("") || pay.contains("a") || pay.contains("b") || pay.contains("c") || pay.contains("d") || pay.contains("e") || pay.contains("v") || pay.contains("u") || pay.contains("x") || pay.contains("y") || pay.contains("z")){
           JOptionPane.showMessageDialog(null,"basic pay number should not be null or incorrect type !");
         }
       else if(acc.equals("")|| acc.contains("a") || acc.contains("b") || acc.contains("c") || acc.contains("d") || acc.contains("e") || acc.contains("v") || acc.contains("u") || acc.contains("x") || acc.contains("y") || acc.contains("z")){
           JOptionPane.showMessageDialog(null,"acc number should not be null or incorrect type !");
         }
       else {
           String sql = "update employee_info set first_name='"+fname1+"',last_name='"+lname1+"',gender='"+g+"',dob='"+db+"',phno='"+ph+"',email='"+em+"',address='"+adrr+"',city='"+cit+"',designation='"+des1+"',basic_pay='"+pay+"',startdate='"+hd+"',accno='"+acc+"',pan='"+p+"'where emp_id ='"+ida+"'";
        
         
         c1.s.execute(sql);
         
         JOptionPane.showMessageDialog(null,"updated"); 
       }
            
            }
            else{
                JOptionPane.showMessageDialog(null,"cannot update please enter a search key");
            }
         } catch (Exception e){
             e.printStackTrace();
         }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        // search 
         String s =search.getText();
        try{
            Connector c1= new Connector();
            String sql="select * from employee_info where emp_id='"+s+"' ";
            //String sq2="select * from bank_details where emp_id='"+s+"'";
            ResultSet rs = c1.s.executeQuery(sql);
            while(rs.next()){
            //rs.next();
            String add1=rs.getString("emp_id");
            id.setText(add1);
            String add2=rs.getString("first_name");
            fname.setText(add2);
            String add3=rs.getString("last_name");
            lname.setText(add3);
            gender.addItem(rs.getString("gender"));
           
            String add5=rs.getString("dob");
           
            java.util.Date date = new SimpleDateFormat("dd/MM/yyyy").parse(add5);
             dob.setDate(date);
           // dob.setText(add5);
            String add6=rs.getString("phno");
            phno.setText(add6);
            String add7=rs.getString("email");
            email.setText(add7);
            String add8=rs.getString("address");
            addr.setText(add8);
            String add9=rs.getString("city");
            city.setText(add9);
            
            desig.addItem(rs.getString("designation"));
        
            String add12=rs.getString("basic_pay");
            bpay.setText(add12);
            
            String add15=rs.getString("startdate");
           
            java.util.Date date3 = new SimpleDateFormat("dd/MM/yyyy").parse(add15);
             hdate.setDate(date3);
            String add16=rs.getString("accno");
            accno.setText(add16);
          String add20 =rs.getString("pan");
           pan.setText(add20);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employeeadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employeeadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employeeadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employeeadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employeeadd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accno;
    private javax.swing.JTextField addr;
    private javax.swing.JTextField bpay;
    private javax.swing.JTextField city;
    private javax.swing.JComboBox<String> desig;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JComboBox<String> gender;
    private com.toedter.calendar.JDateChooser hdate;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField pan;
    private javax.swing.JTextField phno;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables
}
