/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;


import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author devis
 */
public class leav extends javax.swing.JFrame {

    /**
     * Creates new form leav
     */
    public leav() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        empid = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        fd = new com.toedter.calendar.JDateChooser();
        td = new com.toedter.calendar.JDateChooser();
        reason = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(239, 247, 163));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(171, 163, 247));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Employee ID:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(139, 19, 79, 15);
        jPanel2.add(search);
        search.setBounds(248, 17, 240, 30);

        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(520, 20, 120, 23);

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setForeground(new java.awt.Color(255, 51, 51));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(980, 20, 73, 23);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 2, 1060, 80);

        jPanel3.setBackground(new java.awt.Color(171, 163, 247));
        jPanel3.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resume.png"))); // NOI18N
        jPanel3.add(jLabel2);
        jLabel2.setBounds(453, 11, 81, 83);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Employee ID: ");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(138, 72, 82, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("First name: ");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(140, 120, 71, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("leaves:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(140, 160, 70, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("From Date: ");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(140, 210, 71, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("To Date:  ");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(140, 270, 60, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Reason: ");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(140, 330, 70, 17);
        jPanel3.add(empid);
        empid.setBounds(248, 67, 130, 27);
        jPanel3.add(fname);
        fname.setBounds(250, 110, 130, 30);
        jPanel3.add(jSpinner1);
        jSpinner1.setBounds(250, 160, 130, 30);

        fd.setMinSelectableDate(new java.util.Date(1635363109000L));
        jPanel3.add(fd);
        fd.setBounds(250, 210, 130, 30);
        jPanel3.add(td);
        td.setBounds(250, 260, 130, 30);
        jPanel3.add(reason);
        reason.setBounds(250, 320, 130, 30);

        jButton3.setBackground(new java.awt.Color(153, 153, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("APPLY");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(350, 380, 160, 23);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(5, 94, 1070, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1146, 637));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //search
        String s  =search.getText();
        try{
              //String s  =search.getText();
            Connector c = new Connector();
            
            String sql = "select * from employee_info where emp_id ='"+s+"'";
            ResultSet rs = c.s.executeQuery(sql);
            while(rs.next()){
                String id = rs.getString("emp_id");
                empid.setText(id);
                String fname1 =rs.getString("first_name");
                fname.setText(fname1);
            
            }
        }catch(Exception e){
            e.printStackTrace();
        }
            
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        employeehome eh = new employeehome();
        eh.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        // add into database
         String s =search.getText();
         try{
             Connector c = new Connector();
             String fname1 = fname.getText();
             Integer days = (Integer) jSpinner1.getValue();
             SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
           String fd1= df.format(fd.getDate());
           //SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
           String td1= df.format(td.getDate());
           String a = reason.getText();
           String id = empid.getText();
           
           
                   String sql1 = "insert into  leaves(emp_id,days,from_date,to_date,reason) values ('"+id+"','"+days+"','"+fd1+"','"+td1+"','"+a+"')";
                   c.s.execute(sql1);
                   JOptionPane.showMessageDialog(null,"applied sucessfully");
               
           
           
             
             
         }catch(Exception e){
             e.printStackTrace();
         }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(leav.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(leav.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(leav.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(leav.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new leav().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField empid;
    private com.toedter.calendar.JDateChooser fd;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField reason;
    private javax.swing.JTextField search;
    private com.toedter.calendar.JDateChooser td;
    // End of variables declaration//GEN-END:variables
}
