/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

import com.itextpdf.text.Document;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Font;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author devis
 */
public class Payslipadmin extends javax.swing.JFrame {

    /**
     * Creates new form Payslipadmin
     */
    public Payslipadmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        empid = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        dob = new javax.swing.JTextField();
        phno = new javax.swing.JTextField();
        desg = new javax.swing.JTextField();
        bpay = new javax.swing.JTextField();
        startdate = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        finalpay = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(247, 194, 163));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(163, 216, 247));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Employee ID:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(67, 17, 115, 17);
        jPanel2.add(search);
        search.setBounds(192, 12, 199, 30);

        jButton1.setText("search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(409, 16, 73, 23);

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(613, 16, 73, 23);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 20, 710, 70);

        jPanel3.setBackground(new java.awt.Color(163, 216, 247));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Employee ID:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(90, 40, 100, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("First name:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(90, 100, 100, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Date of Birth: ");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(90, 150, 110, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Phone number: ");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(90, 210, 120, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Designation: ");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(410, 40, 100, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Basic Pay: ");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(410, 100, 90, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Start Date:");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(410, 150, 120, 23);
        jPanel3.add(empid);
        empid.setBounds(220, 40, 140, 30);
        jPanel3.add(fname);
        fname.setBounds(220, 90, 140, 30);
        jPanel3.add(dob);
        dob.setBounds(220, 150, 140, 30);
        jPanel3.add(phno);
        phno.setBounds(220, 200, 140, 30);

        desg.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jPanel3.add(desg);
        desg.setBounds(540, 40, 120, 30);

        bpay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(bpay);
        bpay.setBounds(540, 90, 120, 30);
        jPanel3.add(startdate);
        startdate.setBounds(540, 140, 120, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 102));
        jButton3.setText("Generate");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(330, 260, 140, 60);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Final Pay:");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(420, 204, 70, 20);
        jPanel3.add(finalpay);
        finalpay.setBounds(540, 200, 120, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 110, 700, 350);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 9, 1100, 470);

        setSize(new java.awt.Dimension(774, 538));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String s =search.getText();
        try{
            Connector c1= new Connector();
            String sql="select * from employee_info,allowance where employee_info.emp_id='"+s+"' and allowance.emp_id='"+s+"'";
            //String sq2="select * from bank_details where emp_id='"+s+"'";
            ResultSet rs = c1.s.executeQuery(sql);
            while(rs.next()){
            //rs.next();
            String add1=rs.getString("emp_id");
            empid.setText(add1);
            String add2=rs.getString("first_name");
            fname.setText(add2);
            
            String add3=rs.getString("phno");
            phno.setText(add3);
            String add5=rs.getString("dob");
            dob.setText(add5);
            String add11=rs.getString("designation");
            desg.setText(add11);
            String add12=rs.getString("basic_pay");
            bpay.setText(add12);
            
            String add15=rs.getString("startdate");
            startdate.setText(add15);
            String add16=rs.getString("final_pay");
            finalpay.setText(add16);
           
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         String val =empid.getText();
        String val1=fname.getText();
       
        //String val3 =dob.getText();
        
        //String val5 =desg.getText();
        //String val6 =bpay.getText();
        
        //String val8 =startdate.getText();
        //String val9 =finalpay.getText();
        
        
        
        JFileChooser dialog= new JFileChooser();
        dialog.setSelectedFile(new File(val1+"slaray_slip"+".pdf"));
        int dialogResult = dialog.showSaveDialog(null);
        if(dialogResult ==JFileChooser.APPROVE_OPTION){
            String filepath=dialog.getSelectedFile().getPath();
            try{
                Connector ca = new Connector();
                String sql ="select * from allowance,employee_info where employee_info.emp_id='"+val+"' and allowance.emp_id='"+val+"'";
                ResultSet rs =ca.s. executeQuery(sql);
                while(rs.next()){
                    //String val1 =rs.getString("first_name");
                    String val2 =rs.getString("last_name");
                    String val3 =rs.getString("dob");
                    String val4 =rs.getString("designation");
                    //String val5 =rs.getString("dept");
                    String val9 =rs.getString("basic_pay");
                     String val10 =rs.getString("final_pay");
                    
                    
                    String a= rs.getString("deductions");
                    String b =rs.getString("bonus");
                    String h=rs.getString("hike");
                    String ot=rs.getString("overtime");
                    String m =rs.getString("medical");
                    Document myDocument = new Document();
                    PdfWriter myWriter = PdfWriter.getInstance(myDocument, new FileOutputStream(filepath));
                    myDocument.open();
                    
                    myDocument.add(new Paragraph("PAY SLIP",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD )));
                    myDocument.add(new Paragraph(new Date().toString()));
                    myDocument.add(new Paragraph("---------------------------------------**********------------------------------------------------"));
                    myDocument.add((new Paragraph("EMPLOYEE DETAILS",FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.BOLD))));
                    myDocument.add((new Paragraph("Name of Employee: " +val1 + " "+val2,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN))));
                    myDocument.add((new Paragraph("Date of birth: "+val3,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN))));
                    //myDocument.add((new Paragraph("Designation: "+val5,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN))));
                    myDocument.add((new Paragraph("Designation: "+val4,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN))));
                    
                    
                    myDocument.add(new Paragraph("---------------------------------------**********------------------------------------------------"));
                    myDocument.add(new Paragraph("SALARY DETAILS",FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.BOLD)));
                    myDocument.add(new Paragraph("Appraisal: "+h,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
                    myDocument.add(new Paragraph("Basic Salary: Rs "+val9,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
                    myDocument.add(new Paragraph("Overtime: "+ot+" Hours",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
                    myDocument.add(new Paragraph("Medical: Rs " +m,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
                    myDocument.add(new Paragraph("Bonus: Rs "+b,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
                    myDocument.add(new Paragraph("Other: Rs "+a,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
                    myDocument.add(new Paragraph("---------------------------------------**********------------------------------------------------"));
                    myDocument.add(new Paragraph("TOTAL PAYMENT ",FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.BOLD)));
                    myDocument.add(new Paragraph("Total Salary:  Rs "+val10,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
                    myDocument.add(new Paragraph("THANLK YOU",FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.BOLD)));
                    myDocument.add(new Paragraph("---------------------------------------*****ABC CORP*****------------------------------------------------"));
                    myDocument.newPage();
                    myDocument.close();  
                    JOptionPane.showMessageDialog(null,"Report was successfully generated");
                    
                    
                }
                
            
            
            }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null," not sucessful");
            }
                
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Adminhome ad =new Adminhome();
        ad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payslipadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payslipadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payslipadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payslipadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payslipadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bpay;
    private javax.swing.JTextField desg;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField empid;
    private javax.swing.JTextField finalpay;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField phno;
    private javax.swing.JTextField search;
    private javax.swing.JTextField startdate;
    // End of variables declaration//GEN-END:variables
}
