package finalproject;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author devis
 */
public class piechart extends javax.swing.JFrame {

    /**
     * Creates new form piechart
     */
    public piechart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 218, 63));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(63, 92, 247));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("PIECHART");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(230, 10, 230, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 11, 709, 56);

        jPanel3.setBackground(new java.awt.Color(63, 92, 247));
        jPanel3.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\devis\\Downloads\\pie-chart(1).png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(60, 80, 190, 130);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("employee count");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(60, 40, 130, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 80, 710, 370);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(774, 518));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
       JOptionPane.showMessageDialog(null,"appliedd successsfully");
       DefaultPieDataset pieDataset =new DefaultPieDataset();
      
        try{
           
             Connector c = new Connector();
             String a ="Junior";
         
             String sql1="select count(designation)from employee_info where designation='"+a+"'";
            ResultSet rs = c.s.executeQuery(sql1);
           

           if(rs.next()) { 
              int abc = rs.getInt(1);
              pieDataset.setValue("juior",abc);}
         
        }
catch(Exception e ){
    e.printStackTrace();}
        try{
           
             Connector c = new Connector();
             String a ="senior";
         
             String sql1="select count(designation)from employee_info where designation='"+a+"'";
            ResultSet rs = c.s.executeQuery(sql1);
           

           if(rs.next()) { 
              int abc = rs.getInt(1);
              pieDataset.setValue("senior",abc);}
         
        }
catch(Exception e ){
    e.printStackTrace();}
        
        
        try{
           
             Connector c = new Connector();
             String a ="leader";
         
             String sql1="select count(designation)from employee_info where designation='"+a+"'";
            ResultSet rs = c.s.executeQuery(sql1);
           

           if(rs.next()) { 
              int abc = rs.getInt(1);
              pieDataset.setValue("leader",abc);}
         
        }
catch(Exception e ){
    e.printStackTrace();}
        try{
           
             Connector c = new Connector();
             String a ="other";
         
             String sql1="select count(designation)from employee_info where designation='"+a+"'";
            ResultSet rs = c.s.executeQuery(sql1);
           

           if(rs.next()) { 
              int abc = rs.getInt(1);
              pieDataset.setValue("other",abc);}
         
        }
catch(Exception e ){
    e.printStackTrace();}
        
           
         JFreeChart chart = ChartFactory.createPieChart("piechart", pieDataset, true, true,true);
        
         PiePlot p = (PiePlot)chart.getPlot();
         
         //P.setForegroundAlpha(TOP_ALIGNMENT);
         
         
         
         ChartFrame frame=new ChartFrame("Pie chart",chart);
         
         frame.setVisible(true);
         frame.setSize(450,500);
         
         
         
         
         
         
         
         
                 
         
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(piechart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(piechart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(piechart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(piechart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new piechart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}