/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author devis
 */
public class reports extends javax.swing.JFrame {

    /**
     * Creates new form reports
     */
    public reports() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 218, 63));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(63, 92, 247));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("PIE CHARTS ");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(322, 32, 191, 27);
        jButton3.setText("HOME");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(720,30,63,23);
        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 20, 830, 90);

        jPanel4.setBackground(new java.awt.Color(63, 92, 247));
        jPanel4.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(235, 64, 247));
        jPanel5.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pie-chart.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);
        jButton1.setBounds(13, 10, 130, 130);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(60, 90, 150, 150);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setText("EMPLOYEE COUNT");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(70, 50, 130, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pie-chart.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel6);
        jPanel6.setBounds(390, 90, 160, 150);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 153));
        jLabel3.setText("employee payment count ");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(390, 50, 200, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 130, 830, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(900, 675));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
	DefaultPieDataset pieDataset =new DefaultPieDataset();
        
        try{
           
             Connector c = new Connector();
             String a ="Junior";
         
             String sql1="select count(designation)from employee_info where designation='"+a+"'";
            ResultSet rs = c.s.executeQuery(sql1);
           

           if(rs.next()) { 
              int abc = rs.getInt(1);
              pieDataset.setValue("juior",abc);}
         
        }
catch(Exception e ){
    e.printStackTrace();}
        try{
           
             Connector c = new Connector();
             String a ="senior";
         
             String sql1="select count(designation)from employee_info where designation='"+a+"'";
            ResultSet rs = c.s.executeQuery(sql1);
           

           if(rs.next()) { 
              int abc = rs.getInt(1);
              pieDataset.setValue("senior",abc);}
         
        }
catch(Exception e ){
    e.printStackTrace();}
        
        
        try{
           
             Connector c = new Connector();
             String a ="leader";
         
             String sql1="select count(designation)from employee_info where designation='"+a+"'";
            ResultSet rs = c.s.executeQuery(sql1);
           

           if(rs.next()) { 
              int abc = rs.getInt(1);
              pieDataset.setValue("leader",abc);}
         
        }
catch(Exception e ){
    e.printStackTrace();}
try{
            
            Connector c = new Connector();
            String a ="manager";
        
            String sql1="select count(designation)from employee_info where designation='"+a+"'";
           ResultSet rs = c.s.executeQuery(sql1);
          

          if(rs.next()) { 
             int abc = rs.getInt(1);
             pieDataset.setValue("manager",abc);}
        
       }
catch(Exception e ){
    e.printStackTrace();}
        try{
           
             Connector c = new Connector();
             String a ="other";
         
             String sql1="select count(designation)from employee_info where designation='"+a+"'";
            ResultSet rs = c.s.executeQuery(sql1);
           

           if(rs.next()) { 
              int abc = rs.getInt(1);
              pieDataset.setValue("other",abc);}
         
        }
catch(Exception e ){
    e.printStackTrace();}
        
           
         JFreeChart chart = ChartFactory.createPieChart("piechart", pieDataset, true, true,true);
        
         PiePlot p = (PiePlot)chart.getPlot();
         
         //P.setForegroundAlpha(TOP_ALIGNMENT);
         
         
         
         ChartFrame frame=new ChartFrame("Pie chart",chart);
         
         frame.setVisible(true);
         frame.setSize(450,500);
    } 
         
         
         
                 
         
        
        
        
        
        
        
        
    //GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         DefaultPieDataset pieDataset2 =new DefaultPieDataset();
            try{
           
             Connector c = new Connector();
             String a ="paid";
         
             String sql1="select count(status)from allowance where status='"+a+"'";
            ResultSet rs = c.s.executeQuery(sql1);
           

           if(rs.next()) { 
              int abc = rs.getInt(1);
              pieDataset2.setValue("paid",abc);}
         
        }
catch(Exception e ){
    e.printStackTrace();}
        try{
           
             Connector c = new Connector();
             String a ="not paid";
         
             String sql1="select count(status)from allowance where status='"+a+"'";
            ResultSet rs = c.s.executeQuery(sql1);
           

           if(rs.next()) { 
              int abc = rs.getInt(1);
              pieDataset2.setValue("notpaid",abc);}
         
        }
catch(Exception e ){
    e.printStackTrace();} 
        
        JFreeChart chart1 = ChartFactory.createPieChart("piechart", pieDataset2, true, true,true);
         PiePlot p1 = (PiePlot)chart1.getPlot();
        ChartFrame frame1=new ChartFrame("Pie chart",chart1);
        frame1.setVisible(true);
         frame1.setSize(450,500);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     * 
     * 
     */
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
    	Adminhome ah = new Adminhome();
    	ah.setVisible(true);
    	this.dispose();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
