/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author devis
 */
public class resetpass extends javax.swing.JFrame {

    /**
     * Creates new form resetpass
     */
    public resetpass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pin = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        pass2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Enter Password: ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 130, 140, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("ENTER PIN: ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 94, 90, 20);
        jPanel1.add(pin);
        pin.setBounds(260, 80, 150, 30);
        jPanel1.add(pass);
        pass.setBounds(260, 130, 150, 30);
        jPanel1.add(pass2);
        pass2.setBounds(260, 180, 150, 30);

        jButton1.setText("RESET");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(200, 260, 100, 23);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Confirm Password ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(110, 190, 140, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b2.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 50, 474, 295);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("RESET PASSWORD");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(180, 20, 220, 22);

        jButton2.setBackground(new java.awt.Color(255, 0, 255));
        jButton2.setText("HOME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(490, 10, 63, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 570, 430);

        setSize(new java.awt.Dimension(603, 485));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
    	String pi = pin.getText();
        String passw=pass.getText();
        String passw2 =pass2.getText();
        String regex ="^(?=.*[0-9])"+"(?=.*[a-z])(?=.*[A-Z])"+"(?=.*[@#%^&+=])"+"(?=\\S+$).{8,20}$";
        Pattern p = Pattern.compile(regex);
        
        if(pi.equals("")|| passw.equals("") || passw2.equals("")){
            JOptionPane.showMessageDialog(null,"bulll fields");
            
        }
       
           
           
        
        if(passw.equals(passw2)){
            Matcher m =p.matcher(passw);
            
            Boolean m2 =m.matches();
            System.out.println(m2);
            Connector c = new Connector();
            String sql2= "select * from user where pin= '"+pi+"'";
            ResultSet rs = c.s.executeQuery(sql2);
            if(rs.next()) {
            	String u;
                
                   // String ping = rs.getString("pin");
                    u = rs.getString("username");
          
            if(m2){
                String sql3 = "update user set password='"+passw2+"' where username='"+u+"'";
                c.s.execute(sql3);
                JOptionPane.showMessageDialog(null,"password reset success");}
            else {
            	 JOptionPane.showMessageDialog(null,"password reset not success");
            }
           
            //}//while
            	
            }else {
            	 JOptionPane.showMessageDialog(null,"wrong pin");
            }
            
        }//if
           
        }//try 
            
        
        
            
       
            
            
            
        catch(Exception e){
           e.printStackTrace();
            
            
        }
        
        
        
        

        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Adminlgoin ad = new Adminlgoin();
        ad.setVisible(true);
        this.dispose();
        
                
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resetpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resetpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resetpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resetpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resetpass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField pass2;
    private javax.swing.JTextField pin;
    // End of variables declaration//GEN-END:variables
}
