/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

/**
 *
 * @author devis
 */
import java.sql.*;
import javax.swing.table.DefaultTableModel;
public class Searchemployee extends javax.swing.JFrame {

    /**
     * Creates new form Searchemployee
     */
    public Searchemployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        desig = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(48, 242, 251));

        jPanel2.setBackground(new java.awt.Color(251, 157, 148));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("EMPLOYEE ID:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(40, 20, 110, 17);
        jPanel2.add(search);
        search.setBounds(160, 15, 144, 30);

        desig.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        desig.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "senior", "junior", "manager", "leader", "other" }));
        desig.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                desigItemStateChanged(evt);
            }
        });
        desig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desigActionPerformed(evt);
            }
        });
        jPanel2.add(desig);
        desig.setBounds(650, 10, 170, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("DESIGNATION:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(509, 23, 120, 17);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(330, 10, 73, 30);

        jButton2.setBackground(new java.awt.Color(255, 153, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 51, 51));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(950, 20, 100, 30);

        jPanel3.setBackground(new java.awt.Color(251, 157, 148));
        jPanel3.setLayout(null);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(245, 203, 103));
        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employe ID:", "First name", "Date of birth", "Mobile number", "Email", "Designation", "Basic pay", "Acccount number", "Pan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionForeground(new java.awt.Color(245, 203, 103));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 11, 1060, 220);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1086, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1086, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(8, 9, 1096, 543);

        setSize(new java.awt.Dimension(1140, 614));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        //// display the total employee details
        
        
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         DefaultTableModel tb1Model = (DefaultTableModel)jTable1.getModel();
        tb1Model.setRowCount(0);
        try{
            Connector c = new Connector();
            
            String sql = "select * from employee_info";
            ResultSet rs = c.s.executeQuery(sql);
            while(rs.next()){
                String id = rs.getString("emp_id");
                String fname =rs.getString("first_name");
                String dob = rs.getString("dob");
                String mobno =rs.getString("phno");
                String em =rs.getString("email");
                String desig=rs.getString("designation");
                String bpay= rs.getString("basic_pay");
                String acc=rs.getString("accno");
                String pan = rs.getString("pan");
                //String leave= rs.getString("days");
                /// String data for the table
                String tdata[] = {id,fname,dob,mobno,em,desig,bpay,acc,pan};
               
                
                tb1Model.addRow(tdata);
        }
            
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      
        DefaultTableModel tb1Model = (DefaultTableModel)jTable1.getModel();
        tb1Model.setRowCount(0);
        try{
            String s  =search.getText();
            Connector c = new Connector();
            
            String sql = "select * from employee_info where emp_id ='"+s+"'";
            ResultSet rs = c.s.executeQuery(sql);
            while(rs.next()){
                String id = rs.getString("emp_id");
                String fname =rs.getString("first_name");
                String dob = rs.getString("dob");
                String mobno =rs.getString("phno");
                String em =rs.getString("email");
                String desig=rs.getString("designation");
                String bpay= rs.getString("basic_pay");
                String acc=rs.getString("accno");
                String pan = rs.getString("pan");
                //String leave= rs.getString("days");
                /// String data for the table
                String tbdata[] = {id,fname,dob,mobno,em,desig,bpay,acc,pan};
               
                
                tb1Model.addRow(tbdata);
        }
            
        }
        catch(Exception e){
            e.printStackTrace();
        }
            
            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void desigItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_desigItemStateChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_desigItemStateChanged

    private void desigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desigActionPerformed
        // TODO add your handling code here:
         DefaultTableModel tb1Model = (DefaultTableModel)jTable1.getModel();
        tb1Model.setRowCount(0);
        try{
           Object des=desig.getSelectedItem();
            Connector c = new Connector();
            
            String sql = "select * from employee_info where designation ='"+des+"'";
            ResultSet rs = c.s.executeQuery(sql);
            while(rs.next()){
                String id = rs.getString("emp_id");
                String fname =rs.getString("first_name");
                String dob = rs.getString("dob");
                String mobno =rs.getString("phno");
                String em =rs.getString("email");
                String desig=rs.getString("designation");
                String bpay= rs.getString("basic_pay");
                String acc=rs.getString("accno");
                String pan = rs.getString("pan");
                //String leave= rs.getString("days");
                /// String data for the table
                String tbdata[] = {id,fname,dob,mobno,em,desig,bpay,acc,pan};
               
                
                tb1Model.addRow(tbdata);
        }
            
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_desigActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Adminhome ad = new Adminhome();
        ad.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Searchemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Searchemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Searchemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Searchemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Searchemployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> desig;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables
}
